apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - completeautomate.com/protect-deletion
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
