apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  clusterIP: 10.43.5.177
  clusterIPs:
  - 10.43.5.177
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: n8n
  sessionAffinity: None
  type: ClusterIP
