apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: messages-ingress
  namespace: microservices
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`messages.homelab.local`)
      middlewares:
        - name: messages-basic-auth
          namespace: microservices
      services:
        - name: messages-svc
          port: 8000
  tls:
    certResolver: default
