apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment-authelia.yaml
- deployment-redis.yaml
- externalsecret.yaml
- ingress.yaml
- pvc-redis-data.yaml
- service-auth-svc.yaml
- service-redis.yaml
