apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - completeautomate.com/protect-deletion
  name: redis-data
  namespace: authelia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
