apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: linkwarden-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres_password
      remoteRef:
        key: micro-army/linkwarden
        property: postgres_password
    - secretKey: nextauth_secret
      remoteRef:
        key: micro-army/linkwarden
        property: nextauth_secret
    - secretKey: database_url
      remoteRef:
        key: micro-army/linkwarden
        property: database_url
    - secretKey: nextauth_url
      remoteRef:
        key: micro-army/linkwarden
        property: nextauth_url
