apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-postgres.yaml
  - pvc-uploads.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - service.yaml
  - deployment.yaml
  - externalsecret.yaml
