apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-postgres
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
