apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-uploads
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
