apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: ghcr.io/vimalmenon/micro-army/clio
    newTag: v0.0.3
