apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: aws-dynamo-creds
  namespace: microservices
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: aws-dynamo-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: email-smtp-creds
  namespace: microservices
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: email-smtp-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: grafana-admin
    secretNamespace: monitoring
    template:
      data:
        admin-user: '{{ (index . "GRAFANA_ADMIN_USER").Value }}'
        admin-password: '{{ (index . "GRAFANA_ADMIN_PASSWORD").Value }}'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: vaultwarden-secrets
    secretNamespace: vaultwarden
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: immich-postgres
    secretNamespace: immich
    template:
      data:
        POSTGRES_USER: '{{ (index . "IMMICH-POSTGRES_POSTGRES_USER").Value }}'
        POSTGRES_DB: '{{ (index . "IMMICH-POSTGRES_POSTGRES_DB").Value }}'
        POSTGRES_PASSWORD: '{{ (index . "IMMICH-POSTGRES_POSTGRES_PASSWORD").Value }}'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: n8n-secret
    secretNamespace: n8n
    template:
      data:
        auth-password: '{{ (index . "N8N-SECRET_auth-password").Value }}'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: paperless-secrets
    secretNamespace: paperless
    template:
      data:
        postgres_password: '{{ (index . "PAPERLESS-SECRETS_postgres_password").Value }}'
        PAPERLESS_SECRET_KEY: '{{ (index . "PAPERLESS-SECRETS_PAPERLESS_SECRET_KEY").Value }}'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: authelia-secrets
    secretNamespace: authelia
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: aws-dynamo-creds
  namespace: backups
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: aws-dynamo-creds
    secretNamespace: backups
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: linkwarden-secrets
    secretNamespace: linkwarden
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: semaphore-secrets
    secretNamespace: semaphore
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: hestia-secrets
  namespace: microservices
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/hestia"
  managedSecretReference:
    secretName: hestia-secrets
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-token
  namespace: tunnel-sync
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/tunnel-sync"
  managedSecretReference:
    secretName: cloudflare-token
    secretNamespace: tunnel-sync
