apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: aws-dynamo-creds
  namespace: microservices
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: aws-dynamo-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: email-smtp-creds
  namespace: microservices
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: email-smtp-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: grafana-admin
    secretNamespace: monitoring
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: vaultwarden-secrets
    secretNamespace: vaultwarden
