apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: aws-dynamo-creds
  namespace: microservices
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: aws-dynamo-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: email-smtp-creds
  namespace: microservices
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: email-smtp-creds
    secretNamespace: microservices
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: grafana-admin
    secretNamespace: monitoring
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: vaultwarden-secrets
    secretNamespace: vaultwarden
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/immich"
  managedSecretReference:
    secretName: immich-postgres
    secretNamespace: immich
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/n8n"
  managedSecretReference:
    secretName: n8n-secret
    secretNamespace: n8n
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/paperless"
  managedSecretReference:
    secretName: paperless-secrets
    secretNamespace: paperless
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: authelia-secrets
    secretNamespace: authelia
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-token
  namespace: azure-quiz
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: cloudflare-token
    secretNamespace: azure-quiz
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: aws-dynamo-creds
  namespace: backups
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: aws-dynamo-creds
    secretNamespace: backups
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: linkwarden-secrets
    secretNamespace: linkwarden
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
spec:
  authentication:
    kubernetesAuth:
      identityId: "0aad2048-8669-46fa-803e-80f8b4bfbb77"
      serviceAccountRef:
        name: infisical-service-account
        namespace: microservices
      autoCreateServiceAccountToken: true
      secretsScope:
        projectSlug: complete-automate-hpj-t
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: semaphore-secrets
    secretNamespace: semaphore
