apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc-redis.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - infisical-service.yaml
  - infisical-deployment.yaml
  - ingress.yaml
  - ingress-api.yaml
  - infisical-secrets.yaml
