apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: secrets
type: Opaque
stringData:
  postgres_password: "oTPzy8hBPOv2lpAspBQRGyofjwQxojH"
  encryption_key: "4ac0af8f81367e41ffd895b2b26d543c"
  auth_secret: "7e5HShFjYAo7WoXmmtXVbD5R7AFI3YV9+n6v2pNCi64="
  db_connection_uri: "postgresql://infisical:oTPzy8hBPOv2lpAspBQRGyofjwQxojH@postgres.secrets:5432/infisical"
  redis_url: "redis://redis.secrets:6379"
  site_url: "https://secrets.completeautomate.com"
