# ──────────────────────────────────────────────
# homelab-army — Ansible k3s Cluster Inventory
# ──────────────────────────────────────────────
# Run: ansible-playbook -i inventory/hosts.ini playbooks/site.yml
# ──────────────────────────────────────────────

[all:vars]
ansible_user=homelab
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[k3s_master]
homelab01 ansible_host=192.168.128.54

[k3s_workers]
homelab02 ansible_host=192.168.128.64
homelab03 ansible_host=192.168.128.59

[k3s_cluster:children]
k3s_master
k3s_workers
