apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: s3-svc
  namespace: microservices
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: s3-svc
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - microservices
