apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: homelab01
  - matchLabels:
      kubernetes.io/hostname: homelab03
