apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack-secrets
  namespace: notes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: bookstack-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres_password
      remoteRef:
        key: micro-army/bookstack
        property: postgres_password
    - secretKey: database_url
      remoteRef:
        key: micro-army/bookstack
        property: database_url
    - secretKey: app_key
      remoteRef:
        key: micro-army/bookstack
        property: app_key
