apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-mariadb.yaml
  - pvc-uploads.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - service.yaml
  - deployment.yaml
  - externalsecret.yaml
  - ingress.yaml
