apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-uploads
  namespace: notes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
