apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: semaphore-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_password
      remoteRef:
        key: micro-army/semaphore
        property: admin_password
    - secretKey: encryption_key
      remoteRef:
        key: micro-army/semaphore
        property: encryption_key
