apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-data
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
