apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-creds
  namespace: microservices
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: llm-api-creds
  namespace: microservices
type: Opaque
stringData:
  LLM_API_KEY: "sk-5405c8939d244036bca6dee073f1c42f"
