apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-dynamo-creds
  namespace: aws-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: aws-dynamo-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: micro-army/aws-credentials
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: micro-army/aws-credentials
        property: secret_access_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-dynamo-creds
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: aws-dynamo-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: micro-army/aws-credentials
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: micro-army/aws-credentials
        property: secret_access_key
