apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-dynamo-creds
  namespace: aws-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: aws-dynamo-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: micro-army/aws-credentials
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: micro-army/aws-credentials
        property: secret_access_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-dynamo-creds
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: aws-dynamo-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: micro-army/aws-credentials
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: micro-army/aws-credentials
        property: secret_access_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-smtp-creds
  namespace: aws-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: email-smtp-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_host
    - secretKey: SMTP_PORT
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_port
    - secretKey: SMTP_USER
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_user
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_password
    - secretKey: SMTP_FROM
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_from
    - secretKey: SMTP_USE_SSL
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_use_ssl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-smtp-creds
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: email-smtp-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SMTP_HOST
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_host
    - secretKey: SMTP_PORT
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_port
    - secretKey: SMTP_USER
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_user
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_password
    - secretKey: SMTP_FROM
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_from
    - secretKey: SMTP_USE_SSL
      remoteRef:
        key: micro-army/smtp-credentials
        property: smtp_use_ssl
