apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-eso-creds
            key: AWS_ACCESS_KEY_ID
          secretAccessKey:
            name: aws-eso-creds
            key: AWS_SECRET_ACCESS_KEY
