apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-eso-creds
            key: AWS_ACCESS_KEY_ID
            namespace: aws-secrets
          secretAccessKeySecretRef:
            name: aws-eso-creds
            key: AWS_SECRET_ACCESS_KEY
            namespace: aws-secrets
