apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - completeautomate.com/protect-deletion
  name: slides-content
  namespace: slides
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-client
  volumeMode: Filesystem
