apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: microservices
  labels:
    app: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
      annotations:
        rollme: "1"
    spec:
      containers:
      - name: atlas
        image: ghcr.io/vimalmenon/micro-army/s3-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-dynamo-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-dynamo-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_S3_BUCKET
          value: "completeautomate-media"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
