apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch
  namespace: arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arch
  template:
    metadata:
      labels:
        app: arch
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: html
        configMap:
          name: arch-html
          items:
          - key: arch.html
            path: index.html
