---
# Homepage Bookmarks
# https://gethomepage.dev/configs/bookmarks/

- Quick Access:
    - Complete Automate:
        - href: https://completeautomate.com
          description: Main website

    - YouTube Channel:
        - href: https://youtube.com/@real_vimal_menon
          description: real_vimal_menon

    - Gmail:
        - href: https://mail.google.com

    - Linear:
        - href: https://linear.app
