---
# Homepage Bookmarks
# https://gethomepage.dev/configs/bookmarks/

- Quick Access:
    - Complete Automate:
        href: https://completeautomate.com
        icon: completeautomate.png
        description: Main website

    - YouTube Channel:
        href: "https://youtube.com/@real_vimal_menon"
        icon: youtube.png
        description: "real_vimal_menon"

    - Gmail:
        href: https://mail.google.com
        icon: gmail.png

    - Linear:
        href: https://linear.app
        icon: linear.png
