---
# Homepage Widgets
# https://gethomepage.dev/widgets/

- greeting:
        text_size: xl
        text: Complete Automate

- datetime:
        text_size: xl
        format:
            dateStyle: long
            timeStyle: short

- kubernetes:
        cluster:
            show: true
            cpu: true
            memory: false
            showLabel: true
            label: Cluster CPU
        nodes:
            show: false

- kubernetes:
        cluster:
            show: true
            cpu: false
            memory: true
            showLabel: true
            label: Cluster Memory
        nodes:
            show: false

- kubernetes:
        cluster:
            show: false
        nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
