---
# Homepage Widgets
# https://gethomepage.dev/widgets/

- greeting:
    text_size: xl
    text:
      - Complete Automate

- kubernetes:
    cluster:
        show: true
        cpu: true
        memory: true
        showLabel: true
    nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
