---
# Homepage Widgets
# https://gethomepage.dev/widgets/

- datetime:
        text_size: xl
        format:
            dateStyle: long
            timeStyle: short

- kubernetes:
        cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: Cluster
        nodes:
            show: false

- kubernetes:
        cluster:
            show: false
        nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
