apiVersion: apps/v1
kind: Deployment
metadata:
  name: angelos
  namespace: microservices
  labels:
    app: angelos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angelos
  template:
    metadata:
      labels:
        app: angelos
      annotations:
        rollme: "1"
    spec:
      containers:
      - name: angelos
        image: ghcr.io/vimalmenon/micro-army/angelos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: DYNAMO_SVC_URL
          value: http://clio.microservices.svc.cluster.local:8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
