apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: angelos
  namespace: microservices
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: angelos
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - microservices
