apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: couchdb-credentials
  namespace: obsidian-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: couchdb-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_user
      remoteRef:
        key: micro-army/couchdb
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: micro-army/couchdb
        property: admin_password
