apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-sync
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
