apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: nfs-provisioner
    volume.kubernetes.io/storage-provisioner: nfs-provisioner
  finalizers:
  - kubernetes.io/pvc-protection
  name: uptime-kuma-data
  namespace: uptime-kuma
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-b7123b5b-f083-4d3d-93a0-b9223683da1b
