apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hestia-secrets
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: hestia-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api_key
      remoteRef:
        key: micro-army/hestia
        property: api_key
