apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: authelia
    name: authelia
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: metallb-system
      name: metallb-system
    name: metallb-system
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: monitoring
    name: monitoring
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: n8n
    name: n8n
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: netalertx
    name: netalertx
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: nfs-provisioner
    name: nfs-provisioner
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: slides
    name: slides
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      kubernetes.io/metadata.name: uptime-kuma
    name: uptime-kuma
  spec:
    finalizers:
    - kubernetes
kind: List
metadata:
  resourceVersion: ''
