apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vimalmenon/homelab-army.git
    targetRevision: main
    path: services/aws-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
