apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-quiz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vimalmenon/homelab-army.git
    targetRevision: main
    path: services/azure-quiz
  destination:
    server: https://kubernetes.default.svc
    namespace: azure-quiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
