apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-router
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vimalmenon/homelab-army.git
    targetRevision: main
    path: services/kube-router
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
