apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - slides.yaml
  - uptime-kuma.yaml
  - netalertx.yaml
  - n8n.yaml
  - pihole.yaml
  - authelia.yaml
  - grafana-stack.yaml
  - nfs-provisioner.yaml
  - metallb.yaml
  - external-secrets.yaml
  - aws-secrets.yaml
  - dashboards.yaml
  - kube-router.yaml
  - network-policies.yaml
  - homepage.yaml
  - homelab-backup.yaml
  - vaultwarden.yaml
  - cert-manager.yaml
  - cluster-issuer.yaml
  - clio.yaml
  - atlas.yaml
  - athena.yaml
  - orpheus.yaml
  - iris.yaml
  - angelos.yaml
  - arachne.yaml
