apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - slides.yaml
  - uptime-kuma.yaml
  - netalertx.yaml
  - n8n.yaml
  - pihole.yaml
  - authelia.yaml
  - grafana-stack.yaml
  - nfs-provisioner.yaml
  - metallb.yaml
  - dynamo-svc.yaml
  - messages-svc.yaml
  - external-secrets.yaml
  - aws-secrets.yaml
  - s3-svc.yaml
  - email-svc.yaml
  - dashboards.yaml
  - kube-router.yaml
  - network-policies.yaml
  - homepage.yaml
  - homelab-backup.yaml
  - vaultwarden.yaml
  - wiki-svc.yaml
