apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.16.1
      helm:
        releaseName: metallb
        values: |
          frrk8s:
            enabled: false
    - repoURL: https://github.com/vimalmenon/homelab-army.git
      targetRevision: main
      path: infrastructure/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
