apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-sync
  namespace: argocd
spec:
  destination:
    namespace: obsidian-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/obsidian-sync
    repoURL: https://github.com/vimalmenon/homelab-army.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
