apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-data.yaml
  - pvc-postgres.yaml
  - pvc-redis.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
