apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
