apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  namespace: paperless
  labels:
    app: paperless-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: paperless-redis
