apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: "nKoDngKAsZHgVa04EibBtrpNTEl0b0W5/ZbhDzMa0t+WiNrKwEcjdN5dEbZIvWoF"
  postgres_password: "QLCdyhVitwcnI111WuGU6mAdQxbc9"
