apiVersion: v1
kind: Service
metadata:
  name: paperless-web
  namespace: paperless
  labels:
    app: paperless
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: paperless
