apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-data
  namespace: netalertx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
