apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - completeautomate.com/protect-deletion
  name: netalertx-data
  namespace: netalertx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-39b34acd-3181-41ec-b281-712a9189bfb1
