apiVersion: v1
kind: Endpoints
metadata:
  name: hermes-pi-node-exporter
  namespace: monitoring
  labels:
    app: hermes-pi
subsets:
- addresses:
  - ip: 192.168.10.105
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
