apiVersion: v1
kind: Service
metadata:
  annotations:
    svcc.cattle.io/ignore: 'true'
  name: pihole-web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pihole
  type: ClusterIP
