apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-dynamo-creds
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aws-dynamo-creds
  data:
  - remoteRef:
      key: micro-army/aws-credentials
      property: access_key_id
    secretKey: AWS_ACCESS_KEY_ID
  - remoteRef:
      key: micro-army/aws-credentials
      property: secret_access_key
    secretKey: AWS_SECRET_ACCESS_KEY
